version: "3"

services:
  vixen-bot:
    image: pluralkit-vixen
    build: .
    command: ["bin/PluralKit.Bot.dll"]
    environment:
      - "PluralKit__Database=Host=vixen-db;Username=postgres;Password=postgres;Database=postgres;Maximum Pool Size=1000"
      - "PluralKit__RedisAddr=vixen-redis"
      - "PluralKit__InfluxUrl=http://vixen-influx:8086"
      - "PluralKit__InfluxDb=pluralkit-vixen"
      - "PluralKit__LogDir=/var/log/pluralkit-vixen"
      - "PluralKit__Bot__Token=${BOT_TOKEN}"
      - "PluralKit__Bot__ClientId=${CLIENT_ID}"
      - "PluralKit__Bot__AdminRole=${ADMIN_ROLE}"
      - "PluralKit__Bot__ApiUrl=https://api.pluralkit.me/v2"  # Point to official API
    volumes:
      - "/var/log/pluralkit-vixen:/var/log/pluralkit-vixen"
    restart: unless-stopped

#  vixen-api:
#    image: pluralkit-vixen
#    command: ["bin/PluralKit.API.dll"]
#    environment:
#      - "PluralKit__Database=Host=vixen-db;Username=postgres;Password=postgres;Database=postgres;Maximum Pool Size=1000"
#      - "PluralKit__RedisAddr=vixen-redis"
#    ports:
#      - "127.0.0.1:2840:5000"
#    restart: unless-stopped

  vixen-scheduled_tasks:
    image: pluralkit-vixen
    command: ["bin/PluralKit.ScheduledTasks.dll"]
    environment:
      - "PluralKit__Database=Host=vixen-db;Username=postgres;Password=postgres;Database=postgres;Maximum Pool Size=1000"
    restart: unless-stopped

  vixen-db:
    image: postgres:12-alpine
    volumes:
      - "vixen_db_data:/var/lib/postgresql/data"
    command: ["postgres",
              "-c", "max-connections=1000",
              "-c", "timezone=Etc/UTC",
              "-c", "max_wal_size=1GB",
              "-c", "min_wal_size=80MB",
              "-c", "shared_buffers=128MB"]
    environment:
      - "POSTGRES_PASSWORD=postgres"
    restart: unless-stopped

  vixen-redis:
    image: redis:alpine
    restart: unless-stopped

  vixen-influx:
    image: influxdb:1.8
    volumes:
      - "vixen_influx_data:/var/lib/influxdb"
    ports:
      - "127.0.0.1:2841:8086"
    restart: unless-stopped

volumes:
  vixen_db_data:
  vixen_influx_data:
